/*
 * This source file was generated by the Gradle 'init' task
 */
package taller3;

public class App {

   public static void main(String[] args) {
      try 
      {
    
      } catch (Exception e) 
         {
             System.out.println(e);
         }

   }

   /*
    * 1. Construya un algoritmo e implemente la función en Java Escribir_asc que
    * reciba tres números enteros diferentes
    * y devuelva en un String en orden ascendente con el siguiente formato:
    * "##### - ##### - #####", donde el primero es
    * el mayor de todos, el segundo el del medio, el tercero el menor de todos. Si
    * hay al menos dos números iguales,
    * devolverá el mensaje: "Error: La función no considera números iguales". Si
    * hay un error inesperado, deberá mostrar
    * el mensaje: "Ocurrió un error inesperado".
    */
   public static String Escribir_asc(int nro1, int nro2, int nro3){
    try {
        String numeros="";
        int mayor=0, medio=0, menor=0;
        if (nro1 == nro2 || nro1 == nro3 || nro2 == nro3) {
            return "Error: La función no considera números iguales";
        }
        if (nro1 > nro2 && nro1>nro3) {
            mayor=nro1;
            if (nro2>nro3){
            medio=nro2;
            menor=nro3;

            } else {
                medio = nro3;
                menor = nro2;
            }
            
        } else if (nro2 > nro1 && nro2 > nro3){
            mayor= nro2;
            if (nro1>nro3) {
                medio= nro1;
                menor= nro3;
            } else {
                medio= nro3;
                menor= nro1;
            }
        } else if (nro3 > nro1 && nro3 > nro2){
            mayor = nro3;
            if (nro1>nro2) {
                medio= nro1;
                menor= nro2;
            } else {
                medio= nro2;
                menor= nro1;
            }
        }
        numeros= mayor+ " - "+ medio + " - "+menor;
        return numeros;
    
    } catch (Exception e) {
        return "Ocurrió un error inesperado";
    }

   }

   /*
    * 2. Construya un algoritmo e implemente la función en Java Obtener_cifras que
    * recibe un número entre 0 y 50.000
    * y devuelve byte con las cifras que tiene. Por ejemplo 10 tiene dos cifras,
    * 9999 tiene 4 cifras. Si el número
    * no está en el rango devuelve 0. Y si hay un error inesperado, devuelve -1.
    * 
    */
   public static byte Obtener_cifras(int numero){
    try {
        byte cifras=0;
        final byte una=1, dos=2, tres=3, cuatro=4, cinco=5;
        if (numero >= 0 && numero <=50000) {
            if (numero >= 0 && numero <= 9) {
                cifras= una;              
            } else if (numero >=10 && numero <= 99){
                cifras = dos;
            } else if (numero >=100 && numero <= 999){
                cifras = tres;
            } else if (numero >=1000 && numero <= 9999){
                cifras = cuatro;
            } else if (numero >=10000 && numero <= 50000){
                cifras = cinco;
            }
            return cifras;
        } else {
            return 0;
        }
        
    } catch (Exception e) {
        return -1;
    }
   }

   /*
    * 3. Construya un algoritmo e implemente la función en Java Clasificar_char que
    * recibe un caracter, y
    * devuelve un string de acuerdo con las siguientes condiciones: si es un
    * alfabético, deuvelve "ES LETRA";
    * si es numérico, devuelve "ES NUMERO" o si es un carácter especial, devuelve
    * "ESPECIAL".
    * Los caracteres se validan de acuerdo con la tabla ascii básica y lo explicado
    * en clase.
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */
   public static String Clasificar_char(char caracter){
    try {
        String le_num_esp="";
        final char mayus_a='A', mayus_z='Z', min_a= 'a', min_z='z', num1='0', num2='9';
        if (caracter >= mayus_a && caracter <= mayus_z || caracter >= min_a && caracter <= min_z) {
            le_num_esp= "ES LETRA";
        }
        else if (caracter >= num1 && caracter<=num2) {
                le_num_esp= "ES NUMERO";
        } 
        else {
                le_num_esp="ESPECIAL";
            }
            return le_num_esp;
        
    } catch (Exception e) {
        return "Ocurrió un error inesperado";
    }
   }

   /*
    * 
    * 4. Construya un algoritmo e implemente la función en Java
    * Hallar_division_exacta que pida dos números enteros,
    * calcule la división del primero sobre el segundo, y al final si la división
    * es exacta, devuelva "DIVISION EXACTA"
    * y de lo contrario devuelva "DIVISION NO EXACTA". (Exacta significa que tiene
    * cociente, pero no residuo).
    * 
    * Si alguno de los dos números que recibe es cero o negativo, devuelva
    * "NO SE ADMITE CERO O NEGATIVOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * Nota: Revise el funcionamiento del operador mod que le puede ayudar.
    * 
    */
   public static String Hallar_division_exacta(int num1, int num2){
        try {
            String mensaje="";
            
           if (num1 <= 0 || num2 <= 0) {
            return "NO SE ADMITE CERO O NEGATIVOS";
          }
          else if (num1 %num2 ==0) {
            mensaje="DIVISION EXACTA";
            
           } else {
            mensaje="DIVISION NO EXACTA";
           } 
        return mensaje;

        } catch (Exception e) {
            return "Ocurrió un error inesperado";
        }
    }
   

   /*
    * 5. En la siguiente tabla se encuentra la información de las habitaciones de
    * una finca hotel:
    * 
    * Habitación Camas Planta    AA/VENTILADOR
    *    101         2     Primera     AA
    *    102         1     Primera     VE
    *    201         3     Segunda     AA
    *    202         2     Segunda     VE
    *    301         2     Tercera     AA
    * 
    * 
    * Construya un algoritmo e implemente la función en Java Consultar_hab que
    * reciba en un byte el número de camas
    * y en un string si desea VE o AA, y deuvelva en un texto el o los números de
    * habitación que cumplen ese requisito.
    * Si son varias habitaciones, devuelvalas separadas por el caracter |
    * (normalmente, al lado izquierdo de la tecla del 1).
    * Ejemplo: "101|301"
    * Si el número de camas no está entre 1 y 3 o el string es diferente a AA o VE,
    * devuelva "DATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */
   public static String Consultar_hab(byte num_camas, String ve_aa){
        try {
            String respuesta="";
            final String opc_1= "101|301", opc_2="202", opc_3="102", opc_4="201";
            if (num_camas <1 && num_camas >3 || ve_aa != "AA" && ve_aa != "VE") {
                return "DATOS NO VÁLIDOS";
            } else if (num_camas==2 && ve_aa == "AA"){
                respuesta= opc_1;
            }else if (num_camas==2 && ve_aa == "VE"){
                respuesta= opc_2;
            }else if (num_camas==1 && ve_aa == "VE"){
                respuesta=opc_3;
            }else if (num_camas==3 && ve_aa == "AA"){
                respuesta= opc_4;
            }
              return respuesta;  

        } catch (Exception e) {
            return "Ocurrió un error inesperado";
        }
    }

   
   /*
    * 
    * 6. Un restaurante vende 3 platos. Si el cliente solicita el plato 1, le dan
    * el postre gratis; si selecciona los platos
    * 1 y 2, le dan la bebida gratis y si selecciona los platos 1,2 y 3, le dan
    * postre y bebida.
    * Construya un algoritmo e implemente la función Obtener_obs en Java que reciba
    * 3 booleanos, uno para cada plato y en
    * un String devuelva el obsequio ganado en mayúscula, así: "BEBIDA", "POSTRE",
    * "BEBIDA Y POSTRE".
    * Si los 3 platos vienen en false, , devuelva "PLATOS NO VÁLIDOS".
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    */
   public static String Obtener_obs(boolean op1, boolean op2, boolean op3){
        try 
        {
            String obsequio="";
            if (op1==false && op2==false && op3==false) {
                return "PLATOS NO VÁLIDOS";
            }
                else if (op1 == true && op2==false && op3==false) {
                        obsequio="POSTRE"; 
                    }
                    else if (op1 == true && op2== true && op3 == false) {
                        obsequio="BEBIDA"; 
                        } 
                        else if (op1 == true && op2== true && op3== true) {
                                obsequio="BEBIDA Y POSTRE"; 
                                }
                            
                return obsequio;
            
        }
        catch (Exception e) 
        {
            return "Ocurrió un error inesperado" ;
        }
    }

   /*
    * 7. Un grupo de amigos hace un sorteo semanalmente con pelotas de ping pong,
    * para saber quién invita y a qué  la próxima salida.
    * Las opciones dependen del color que sacan en cada bola y son:
    * 
    * verde: Invita a las cervezas
    * azul: Invita a la pizza
    * rojo: Invita al postre
    * amarillo: Paga el parqueadero de todos
    * blanco o negro: Vaya y disfrute
    * Si la función recibe algo diferente a los colores dados, debe retornar
    * "Error en el color".
    * 
    * Se necesita una función en java Conocer_invitacion que reciba un string con
    * el color de la bola y retorna un
    * String con exactamente el texto de la invitación correspondiente.
    * 
    * Si hay un error inesperado, deberá mostrar el mensaje:
    * "Ocurrió un error inesperado".
    * 
    */
   public static String Conocer_invitacion(String color){
        try {
            String gana="";

            if (!color.equals("verde") && !color.equals("azul") && !color.equals("rojo") 
            && !color.equals("amarillo") && !color.equals("blanco") && !color.equals("negro") ) {
                return  "Error en el color";
            } else {
                switch (color) {
                    case "verde":
                        gana= "Invita a las cervezas";
                        break;
                    case "azul":
                        gana= "Invita a la pizza";
                        break;
                    case "rojo":
                        gana= "Invita al postre";
                        break;
                    case "amarillo":
                        gana= "Paga el parqueadero de todos";
                        break;
                    case "blanco":
                        gana= "Vaya y disfrute";
                        break;
                    case "negro":
                        gana= "Vaya y disfrute";
                        break;
                }    
                return gana;
            }
       
            
        } catch (Exception e) {
            return "Ocurrió un error inesperado";
        }
    }
}
